#!/usr/bin/env python3
"""
CMSSW ROOT-to-viewer processing pipeline.

This module keeps the CMSSW execution and browser-bundle generation in one
place so the server and local CLI use identical behavior.
"""

from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import sys
import threading
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable
from urllib.parse import urlparse
from urllib.request import urlretrieve


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_CMSSW_RELEASE = os.environ.get("TRUTHVIZ_CMSSW_RELEASE", "CMSSW_20_1_0_pre3")
DEFAULT_CMSSW_SRC = PROJECT_ROOT.parent / DEFAULT_CMSSW_RELEASE / "src"


class PipelineError(RuntimeError):
    """Raised when an input processing job cannot complete."""


@dataclass
class PipelineOptions:
    event_index: int = 0
    dumper_args: list[str] = field(default_factory=list)
    job_id: str | None = None
    job_root: Path | None = None
    cmssw_src: Path | None = None
    cmsrun_timeout: int | None = None
    cmsrun_wrapper: str | None = None
    debug_dir: Path | None = None
    copy_to_viewer: bool = True


@dataclass
class PipelineResult:
    job_id: str
    job_dir: Path
    cmssw_outdir: Path
    dot_path: Path
    rechits_root_path: Path
    bundle_path: Path
    rechits_json_path: Path
    viewer_bundle_path: Path | None
    viewer_rechits_path: Path | None
    debug_dir: Path | None = None

    def as_dict(self) -> dict:
        return {
            "jobId": self.job_id,
            "jobDir": str(self.job_dir),
            "cmsswOutdir": str(self.cmssw_outdir),
            "dotPath": str(self.dot_path),
            "rechitsRootPath": str(self.rechits_root_path),
            "bundlePath": str(self.bundle_path),
            "rechitsJsonPath": str(self.rechits_json_path),
            "viewerBundlePath": str(self.viewer_bundle_path) if self.viewer_bundle_path else None,
            "viewerRechitsPath": str(self.viewer_rechits_path) if self.viewer_rechits_path else None,
            "debugDir": str(self.debug_dir) if self.debug_dir else None,
        }


def default_job_root(project_root: Path = PROJECT_ROOT) -> Path:
    return Path(os.environ.get("TRUTHVIZ_JOB_ROOT", project_root / "data" / "jobs")).expanduser()


def resolve_cmssw_src(explicit: str | Path | None = None) -> Path:
    if explicit:
        return Path(explicit).expanduser().resolve()

    env_src = os.environ.get("TRUTHVIZ_CMSSW_SRC")
    if env_src:
        return Path(env_src).expanduser().resolve()

    cmssw_base = os.environ.get("CMSSW_BASE")
    if cmssw_base:
        return Path(cmssw_base).expanduser().resolve() / "src"

    local_candidates = (
        PROJECT_ROOT / DEFAULT_CMSSW_RELEASE / "src",
        PROJECT_ROOT / "data" / "cmssw" / DEFAULT_CMSSW_RELEASE / "src",
        DEFAULT_CMSSW_SRC,
    )
    for candidate in local_candidates:
        if candidate.exists():
            return candidate.resolve()

    return DEFAULT_CMSSW_SRC.resolve()


def parse_non_negative_int(value, name: str) -> int:
    try:
        number = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be a non-negative integer") from exc
    if number < 0:
        raise ValueError(f"{name} must be a non-negative integer")
    return number


def parse_dumper_args(args_text: str | None) -> list[str]:
    if not args_text:
        return []
    return shlex.split(args_text)


def validate_cmssw_src(cmssw_src: Path) -> None:
    if not cmssw_src.exists():
        raise PipelineError(
            f"CMSSW src directory does not exist: {cmssw_src}. "
            "Set TRUTHVIZ_CMSSW_SRC to a CMSSW_20_1_0_pre3/src directory "
            "or start the app with ./run.sh while CVMFS is mounted."
        )
    cfg = cmssw_src / "PhysicsTools" / "TruthInfo" / "test" / "dumpTruthGraphsFromGENSIMRECO_cfg.py"
    if not cfg.exists():
        raise PipelineError(f"CMSSW dumper config not found: {cfg}")


def cmssw_input_arg(input_root: Path) -> str:
    input_arg = str(input_root)
    if ":" not in input_arg:
        input_arg = f"file:{input_arg}"
    return input_arg


def write_cmsrun_wrapper_config(
    wrapper_path: Path,
    cfg_path: Path,
    input_root: Path,
    outdir: Path,
    options: PipelineOptions,
) -> Path:
    """Write a cmsRun config that adds event skipping without requiring cfg support."""
    args = [
        cmssw_input_arg(input_root),
        "-n",
        "1",
        "-o",
        str(outdir),
    ]
    args.extend(options.dumper_args)

    wrapper_path.parent.mkdir(parents=True, exist_ok=True)
    wrapper_path.write_text(
        f"""# Auto-generated by CMSSWGraphViz/truth_pipeline.py.
import runpy
import sys
import FWCore.ParameterSet.Config as cms
from Configuration.ProcessModifiers.alpaka_cff import alpaka

_original_argv = sys.argv[:]
sys.argv = [{str(wrapper_path)!r}] + {args!r}
_original_process = cms.Process
class _AlpakaProcess(_original_process):
    def __init__(self, *process_args, **process_kwargs):
        super().__init__(*process_args, alpaka, **process_kwargs)

cms.Process = _AlpakaProcess
try:
    _namespace = runpy.run_path({str(cfg_path)!r})
finally:
    cms.Process = _original_process
    sys.argv = _original_argv

process = _namespace["process"]
process.load("Configuration.StandardSequences.Services_cff")
process.options.accelerators = cms.untracked.vstring("*")
process.source.skipEvents = cms.untracked.uint32({options.event_index})
# The interactive rechit panel matches the ROOT-exported coordinates to the
# DetIds written on logical-graph particles.  The CMSSW dumper defaults to
# omitting that list, which leaves hit counts in the DOT but nothing for the
# browser to select.
process.truthLogicalGraphDumper.dumpSimHits = cms.bool(True)
""",
        encoding="utf-8",
    )
    return wrapper_path


def cmsrun_command(cmssw_src: Path, cfg_path: Path) -> str:
    quoted_args = " ".join(shlex.quote(arg) for arg in ["cmsRun", str(cfg_path)])
    quoted_src = shlex.quote(str(cmssw_src))
    return f"cd {quoted_src} && CMSSW_ENV=$(scram runtime -sh) && eval \"$CMSSW_ENV\" && {quoted_args}"


def update_status(callback: Callable[..., None] | None, **updates) -> None:
    if callback is not None:
        callback(**updates)


def run_process_with_live_output(
    args,
    *,
    cwd: Path,
    timeout: int | None,
    phase: str,
    status_callback: Callable[..., None] | None = None,
    log_path: Path | None = None,
) -> subprocess.CompletedProcess:
    """Run a process while forwarding each stdout/stderr line to the job."""
    command = shlex.join(str(arg) for arg in args)
    log_file = None
    log_lock = threading.Lock()

    if log_path is not None:
        log_path = Path(log_path)
        log_path.parent.mkdir(parents=True, exist_ok=True)
        log_file = log_path.open("a", encoding="utf-8")

    def record_log(text: str) -> None:
        if log_file is None:
            return
        with log_lock:
            log_file.write(text)
            log_file.flush()

    record_log(f"===== {phase} =====\n$ {command}\n")
    update_status(status_callback, log=f"===== {phase} =====\n$ {command}\n")
    output = {"stdout": [], "stderr": []}
    try:
        process = subprocess.Popen(
            args,
            cwd=cwd,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
            env={**os.environ, "PYTHONUNBUFFERED": "1"},
        )
    except OSError as exc:
        record_log(f"[failed to start: {exc}]\n")
        update_status(status_callback, log=f"[failed to start: {exc}]\n")
        if log_file is not None:
            log_file.close()
        raise

    def forward(stream_name: str, stream) -> None:
        try:
            for line in iter(stream.readline, ""):
                output[stream_name].append(line)
                record_log(f"[{stream_name}] {line}")
                update_status(status_callback, log=f"[{stream_name}] {line}")
        finally:
            stream.close()

    readers = [
        threading.Thread(target=forward, args=(name, getattr(process, name)), daemon=True)
        for name in ("stdout", "stderr")
    ]
    for reader in readers:
        reader.start()

    timed_out = False
    try:
        returncode = process.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        timed_out = True
        process.kill()
        returncode = process.wait()
    for reader in readers:
        reader.join()

    result = subprocess.CompletedProcess(
        args,
        returncode,
        stdout="".join(output["stdout"]),
        stderr="".join(output["stderr"]),
    )
    record_log(f"[process exited with code {returncode}]\n")
    update_status(status_callback, log=f"[process exited with code {returncode}]\n")
    try:
        if timed_out:
            raise PipelineError(f"{phase} timed out after {timeout} seconds")
        return result
    finally:
        if log_file is not None:
            log_file.close()


def run_checked(
    args,
    *,
    cwd: Path,
    timeout: int | None,
    phase: str,
    status_callback: Callable[..., None] | None = None,
    log_path: Path | None = None,
) -> subprocess.CompletedProcess:
    result = run_process_with_live_output(
        args,
        cwd=cwd,
        timeout=timeout,
        phase=phase,
        status_callback=status_callback,
        log_path=log_path,
    )
    if result.returncode != 0:
        output = "\n".join(part for part in [result.stdout, result.stderr] if part).strip()
        raise PipelineError(f"{phase} failed with exit code {result.returncode}: {output or 'no output'}")
    return result


def cmsrun_subprocess_args(command: str, wrapper: str | None) -> list[str]:
    if wrapper:
        return [*shlex.split(wrapper), "--command-to-run", command]
    return ["bash", "-lc", command]


def find_single_newest(pattern: str, directory: Path, label: str) -> Path:
    matches = sorted(directory.glob(pattern), key=lambda path: path.stat().st_mtime, reverse=True)
    if not matches:
        raise PipelineError(f"No {label} found in {directory} matching {pattern}")
    return matches[0]


def process_cmssw_root(input_root: Path, options: PipelineOptions | None = None, status_callback=None) -> PipelineResult:
    options = options or PipelineOptions()
    options.event_index = parse_non_negative_int(options.event_index, "eventIndex")

    input_root = Path(input_root).expanduser().resolve()
    if not input_root.exists():
        raise PipelineError(f"Input ROOT file does not exist: {input_root}")

    cmssw_src = resolve_cmssw_src(options.cmssw_src)
    validate_cmssw_src(cmssw_src)

    job_root = Path(options.job_root).expanduser().resolve() if options.job_root else default_job_root().resolve()
    job_id = options.job_id or f"{int(time.time())}-{uuid.uuid4().hex[:8]}"
    job_dir = job_root / job_id
    cmssw_outdir = job_dir / "cmssw"
    bundle_path = job_dir / "bundle.json"
    rechits_json_path = job_dir / "rechits.json"
    job_dir.mkdir(parents=True, exist_ok=True)
    cmssw_outdir.mkdir(parents=True, exist_ok=True)

    debug_root = options.debug_dir
    if debug_root is None:
        debug_root = os.environ.get("TRUTHVIZ_DEBUG_DIR")
    debug_dir = None
    if debug_root:
        debug_dir = Path(debug_root).expanduser().resolve() / job_id
        try:
            debug_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise PipelineError(f"Could not create debug directory {debug_dir}: {exc}") from exc
    pipeline_log_path = debug_dir / "pipeline.log" if debug_dir else None

    timeout = options.cmsrun_timeout
    if timeout is None:
        timeout = int(os.environ.get("TRUTHVIZ_CMSRUN_TIMEOUT_SEC", "3600"))

    cfg_path = cmssw_src / "PhysicsTools" / "TruthInfo" / "test" / "dumpTruthGraphsFromGENSIMRECO_cfg.py"
    wrapper_cfg_path = write_cmsrun_wrapper_config(
        job_dir / "dumpTruthGraphs_wrapper_cfg.py",
        cfg_path,
        input_root,
        cmssw_outdir,
        options,
    )
    if debug_dir is not None and debug_dir != job_dir:
        shutil.copyfile(wrapper_cfg_path, debug_dir / wrapper_cfg_path.name)
    command = cmsrun_command(cmssw_src, wrapper_cfg_path)
    wrapper = options.cmsrun_wrapper or os.environ.get("TRUTHVIZ_CMSRUN_WRAPPER")
    cmsrun_args = cmsrun_subprocess_args(command, wrapper)

    update_status(status_callback, phase="cmsrun", message=f"Running cmsRun for event {options.event_index}...")
    result = run_process_with_live_output(
        cmsrun_args,
        cwd=cmssw_src,
        timeout=timeout,
        phase="cmsRun",
        status_callback=status_callback,
        log_path=pipeline_log_path,
    )
    (job_dir / "cmsrun.stdout.log").write_text(result.stdout or "", encoding="utf-8")
    (job_dir / "cmsrun.stderr.log").write_text(result.stderr or "", encoding="utf-8")
    if debug_dir is not None and debug_dir != job_dir:
        (debug_dir / "cmsrun.stdout.log").write_text(result.stdout or "", encoding="utf-8")
        (debug_dir / "cmsrun.stderr.log").write_text(result.stderr or "", encoding="utf-8")
    if result.returncode != 0:
        output = "\n".join(part for part in [result.stdout, result.stderr] if part).strip()
        raise PipelineError(f"cmsRun failed with exit code {result.returncode}: {output or 'no output'}")

    dot_path = find_single_newest("truthlogicalgraph*_run*_lumi*_event*.dot", cmssw_outdir, "logical DOT file")
    rechits_root_path = find_single_newest("rechits_nano*.root", cmssw_outdir, "rechits ROOT file")

    update_status(status_callback, phase="bundle", message="Building browser graph bundle...")
    run_checked(
        [
            sys.executable,
            str(PROJECT_ROOT / "preprocess" / "build_bundle.py"),
            str(dot_path),
            str(bundle_path),
            "--no-js-output",
        ],
        cwd=PROJECT_ROOT,
        timeout=1800,
        phase="Bundle generation",
        status_callback=status_callback,
        log_path=pipeline_log_path,
    )

    update_status(status_callback, phase="rechits", message="Building rechits JSON...")
    run_checked(
        [
            sys.executable,
            str(PROJECT_ROOT / "preprocess" / "build_rechits_json.py"),
            str(rechits_root_path),
            str(rechits_json_path),
            "--event-index",
            "0",
            "--no-js-output",
        ],
        cwd=PROJECT_ROOT,
        timeout=1800,
        phase="Rechits generation",
        status_callback=status_callback,
        log_path=pipeline_log_path,
    )

    viewer_bundle_path = None
    viewer_rechits_path = None
    if options.copy_to_viewer:
        update_status(status_callback, phase="viewer", message="Publishing generated files to the viewer...")
        viewer_bundle_path = PROJECT_ROOT / "data" / "bundle.json"
        viewer_rechits_path = PROJECT_ROOT / "data" / "rechits.json"
        viewer_bundle_js_path = PROJECT_ROOT / "app" / "js" / "bundle.js"
        viewer_rechits_js_path = PROJECT_ROOT / "app" / "js" / "rechits.js"
        viewer_bundle_path.parent.mkdir(parents=True, exist_ok=True)
        viewer_bundle_js_path.parent.mkdir(parents=True, exist_ok=True)

        # OpenShift volumes may reject chmod/copymode even when writes are allowed.
        # copyfile copies bytes only, unlike copy/copy2.
        shutil.copyfile(bundle_path, viewer_bundle_path)
        shutil.copyfile(rechits_json_path, viewer_rechits_path)
        run_checked(
            [
                sys.executable,
                str(PROJECT_ROOT / "preprocess" / "generate_bundle_js.py"),
                str(viewer_bundle_path),
                str(viewer_bundle_js_path),
            ],
            cwd=PROJECT_ROOT,
            timeout=1800,
            phase="Static bundle JS generation",
            status_callback=status_callback,
            log_path=pipeline_log_path,
        )
        run_checked(
            [
                sys.executable,
                str(PROJECT_ROOT / "preprocess" / "build_rechits_json.py"),
                str(rechits_root_path),
                str(viewer_rechits_path),
                "--event-index",
                "0",
                "--js-output",
                str(viewer_rechits_js_path),
            ],
            cwd=PROJECT_ROOT,
            timeout=1800,
            phase="Static rechits JS generation",
            status_callback=status_callback,
            log_path=pipeline_log_path,
        )

    return PipelineResult(
        job_id=job_id,
        job_dir=job_dir,
        cmssw_outdir=cmssw_outdir,
        dot_path=dot_path,
        rechits_root_path=rechits_root_path,
        bundle_path=bundle_path,
        rechits_json_path=rechits_json_path,
        viewer_bundle_path=viewer_bundle_path,
        viewer_rechits_path=viewer_rechits_path,
        debug_dir=debug_dir,
    )


def catalog_path(project_root: Path = PROJECT_ROOT) -> Path:
    return Path(os.environ.get("TRUTHVIZ_CATALOG", project_root / "samples" / "catalog.json")).expanduser()


def load_catalog(path: Path | None = None) -> dict:
    path = Path(path).expanduser() if path else catalog_path()
    if not path.exists():
        return {"samples": []}
    with open(path, encoding="utf-8") as handle:
        data = json.load(handle)
    samples = data.get("samples", [])
    if not isinstance(samples, list):
        raise PipelineError("Sample catalog must contain a 'samples' list")
    return {"samples": samples}


def find_catalog_sample(sample_id: str, path: Path | None = None) -> dict:
    catalog = load_catalog(path)
    for sample in catalog["samples"]:
        if sample.get("id") == sample_id:
            return sample
    raise PipelineError(f"Sample not found in catalog: {sample_id}")


def materialize_catalog_sample(sample: dict, job_dir: Path) -> Path:
    if "path" in sample:
        sample_path = Path(sample["path"]).expanduser()
        if not sample_path.is_absolute():
            sample_path = (catalog_path().parent / sample_path).resolve()
        else:
            sample_path = sample_path.resolve()
        if not sample_path.exists():
            raise PipelineError(f"Catalog sample path does not exist: {sample_path}")
        return sample_path

    if "url" in sample:
        url = sample["url"]
        parsed = urlparse(url)
        if parsed.scheme not in {"http", "https"}:
            raise PipelineError(f"Unsupported catalog sample URL scheme: {parsed.scheme}")
        destination = job_dir / "input.root"
        urlretrieve(url, destination)
        return destination

    raise PipelineError("Catalog sample must define either 'path' or 'url'")
